-- parses a file's syntax
-- ensure_installed downloads and makes syntax files available for Treesitter
-- this allows any plugin which uses Treesitter access to those parsers
-- also used for highlighting code blocks in Markdown
--
-- used by:
-- - obsidian.nvim (syntax hilighting)
-- - trouble.nvim (hilighting code in window)
-- - vsnip (support for injected/embedded languages)
-- - telescope.nvim (hilighting in pop-up windows)
-- - codewindow.nvim (coloring the dots in the overview)
--
-- https://github.com/nvim-treesitter/nvim-treesitter

local xei = require 'xei'
xei.plugin('nvim-treesitter.configs', {
  ensure_installed = {
    'asm',
    'bash',
    'c',
    'cmake',
    'comment',
    'cpp',
    'css',
    'csv',
    'desktop',
    'diff',
    'disassembly',
    'dockerfile',
    'dot',
    'editorconfig',
    'elixir',
    'erlang',
    'faust',
    'fennel',
    'fish',
    'forth',
    'gdscript',
    'gdshader',
    'git_config',
    'git_rebase',
    'gitattributes',
    'gitcommit',
    'gitignore',
    'glsl',
    'go',
    'godot_resource',
    'gomod',
    'gosum',
    'gpg',
    'haskell',
    'html',
    'http',
    'ini',
    'jq',
    'json',
    'julia',
    'latex',
    'llvm',
    'lua',
    'luadoc',
    'luap',
    'm68k',
    'make',
    'markdown',
    'markdown_inline',
    'nasm',
    'nginx',
    'nim',
    'nim_format_string',
    'ninja',
    'nim',
    'norg',
    'objc',
    'objdump',
    'ocaml',
    'ocaml_interface',
    'pascal',
    'passwd',
    'pem',
    'perl',
    'pod',
    'pony',
    'powershell',
    'printf',
    'python',
    'regex',
    'robots',
    'rst',
    'ruby',
    'rust',
    'slim',
    'sql',
    'ssh_config',
    'strace',
    'supercollider',
    'swift',
    'tablegen',
    'tmux',
    'toml',
    'typescript',
    'v',
    'vim',
    'vimdoc',
    'xcompose',
    'xresources',
    'yaml',
    'zig',
  },
  highlight = {
    enable = true,
  },
}, 'silent')
