#!/usr/bin/env bash

# Archives the system's dotfiles
# Creates symlinks to the new dotfiles
# Put this in a SCM repo such as mercurial, git, or monotone with the dotfiles you want to install on multiple systems.
# Put all the dotfiles in the same directory as the install script and list them in the file variable.
# run with `./install`

echo -ne "pushd: "
pushd `dirname $0`

dir=`pwd`
dot_dir=$dir/dotfiles
cd $dot_dir

mkdir -v backup

  do
    if [ -h ~/$i ]
      then
        echo -ne "rm: symlink "
        rm -v ~/$i
      else
        if [ -f ~/$i ]
          then
            echo -ne "backup - "
            mv -v ~/$i backup
        fi
for i in *; do
    fi
    echo -ne "ln: "
    ln -v -s $dot_dir/$i ~/$i
  done
#end for

echo Pulling remote submodules...
git submodule update --init
git submodule foreach "git pull"

echo Sourcing .bash_profile...
source ~/.bash_profile

echo Done!
