#!/usr/bin/env bash

# Archives the system's dotfiles
# Creates symlinks to the new dotfiles
# Put this in a SCM repo such as mercurial, git, or monotone with the dotfiles you want to install on multiple systems.
# Put all the dotfiles in the same directory as the install script and list them in the file variable.
# run with `./install`

files=( .bash_profile .gitconfig .vim .vimrc .bash_completion .hgrc )

echo -ne Changing directory to `dirname $0` -\ 
pushd `dirname $0`
dir=`pwd`

echo -ne Creating backup directory -\ 
mkdir -v backup

for i in "${files[@]}" 
do
  if [ -h ~/$i ] 
    then
      echo -ne nop -\ 
      echo ~/$i is symlink, not backing up
      rm ~/$i
    else
      if [ -f ~/$i ]
        then
          echo -ne backup -\ 
          mv -v ~/$i backup
      fi
  fi
  echo -ne link -\ 
  ln -v -s $dir/$i ~/$i
done

echo Sourcing .bash_profile...
source ~/.bash_profile

echo Done!
