#!/usr/bin/env bash

cd `dirname $0`
echo Stashing local changes...
git stash
echo Updating local repo...
git pull --rebase origin master
echo Updating remote submodules...
git submodule update --init --recursive
git submodule foreach "git fetch -q && git checkout -q origin/HEAD"
echo Restoring local changes...
git unstash
echo Updating Vim plugins...
vim -e +PlugUpgrade +PlugUpdate +qa!
echo Done!
